# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pidge < Formula
  desc "Share a single HTML page, briefly."
  homepage "https://pidge.to"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.4/pidge_0.1.4_darwin_amd64.tar.gz"
      sha256 "ec31f544d285e084b9bd836b29347587215ff1426ab29e77d6c2eaefdc0cd386"

      define_method(:install) do
        bin.install "pidge"
        man1.install "cli/man/pidge.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.4/pidge_0.1.4_darwin_arm64.tar.gz"
      sha256 "4d295103f2cdc8ee2181bcc3ff151e84f9b4a65579351c66918a3c7d5c4269ff"

      define_method(:install) do
        bin.install "pidge"
        man1.install "cli/man/pidge.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.4/pidge_0.1.4_linux_amd64.tar.gz"
      sha256 "97adf3172130527fe3806e305bb1ef2248d4477639b25f8673dde0566fd57890"
      define_method(:install) do
        bin.install "pidge"
        man1.install "cli/man/pidge.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.4/pidge_0.1.4_linux_arm64.tar.gz"
      sha256 "a3b0704e87be14913c5b3b92229befd65f25c6c3e8cf7f82201ebd38d729547e"
      define_method(:install) do
        bin.install "pidge"
        man1.install "cli/man/pidge.1"
      end
    end
  end

  test do
    system "#{bin}/pidge", "--version"
  end
end
