# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pidge < Formula
  desc "Share a single HTML page, briefly."
  homepage "https://pidge.to"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iiAtlas/pidge.to/releases/download/v0.1.0/pidge_0.1.0_darwin_amd64.tar.gz"
      sha256 "56b78f695ef04df511bad45d33d2b5b46309691feccf7afe211fd4be399fedf9"

      define_method(:install) do
        bin.install "pidge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iiAtlas/pidge.to/releases/download/v0.1.0/pidge_0.1.0_darwin_arm64.tar.gz"
      sha256 "577daa8bb89c74bc99a8ce3308ac8c08e193e644a79c9ccdbfb7b11f4048e987"

      define_method(:install) do
        bin.install "pidge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iiAtlas/pidge.to/releases/download/v0.1.0/pidge_0.1.0_linux_amd64.tar.gz"
      sha256 "1266502918c34eb6073be6da342656e8f9595c41516083c9141b2682daf908ca"
      define_method(:install) do
        bin.install "pidge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iiAtlas/pidge.to/releases/download/v0.1.0/pidge_0.1.0_linux_arm64.tar.gz"
      sha256 "13b982b03f3a782adf2b1e49e60a2a8d4c600cb710182b71d4e3a6cfcc39aca7"
      define_method(:install) do
        bin.install "pidge"
      end
    end
  end

  test do
    system "#{bin}/pidge", "--help"
  end
end
