# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdv-gui" do
  name "mdv-gui"
  desc "Native GUI markdown viewer"
  homepage "https://github.com/iiatlas/mdv"
  version "1.0.20"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdv-gui"

  on_macos do
    on_intel do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv- gui_#{version}_darwin_x86_64.tar.gz"
      sha256 "ff24bfa6b1ea2358e3530b475e201e536d3f0dcd6718b1d17bef5f365caf9336"
    end
    on_arm do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv- gui_#{version}_darwin_arm64.tar.gz"
      sha256 "dee308630e5930d8fbb2b9fa137d8a54a1200493305644bbd8b3f5246eab7c64"
    end
  end

  # No zap stanza required
end
