# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdv-tui" do
  name "mdv-tui"
  desc "Terminal-based markdown viewer (TUI only)"
  homepage "https://github.com/iiatlas/mdv"
  version "1.0.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdv"

  on_linux do
    on_intel do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv- tui_#{version}_linux_x86_64.tar.gz"
      sha256 "60a80b83fcc8a50fc9dbe289eeb0542686b97c6c2f90f4fa1b14b5391de4e18d"
    end
    on_arm do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv- tui_#{version}_linux_arm64.tar.gz"
      sha256 "17851058f908d5db28ea78b3f6fd06a86226d71db336530f9a781c60c9af65ff"
    end
  end

  # No zap stanza required
end
