# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdv-gui" do
  name "mdv-gui"
  desc "Native GUI markdown viewer"
  homepage "https://github.com/iiatlas/mdv"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdv-gui"

  on_macos do
    on_intel do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv-gui_#{version}_darwin_x86_64.tar.gz"
      sha256 "1e0caedd5105213fff41a5667baf2340ee9205690a8e1e1e30438909d4cece94"
    end
    on_arm do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv-gui_#{version}_darwin_arm64.tar.gz"
      sha256 "0de334cd3c5de72c8faffdce08c89c478e48cc3ea2c98fd4f536edc9358e2287"
    end
  end

  # No zap stanza required
end
