# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdv-tui" do
  name "mdv-tui"
  desc "Terminal-based markdown viewer (TUI only)"
  homepage "https://github.com/iiatlas/mdv"
  version "1.0.21"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdv"

  on_linux do
    on_intel do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv- tui_#{version}_linux_x86_64.tar.gz"
      sha256 "b24e6b0368e4830b42bceb92e58742d82b7de68634d8dccb67f1f7329c6f095d"
    end
    on_arm do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv- tui_#{version}_linux_arm64.tar.gz"
      sha256 "5ec314f3cc4ad4d91e285691d579293f8cb83f9c5ff47dc05f0b108472f40c99"
    end
  end

  # No zap stanza required
end
