# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdv-gui" do
  name "mdv-gui"
  desc "Native GUI markdown viewer"
  homepage "https://github.com/iiatlas/mdv"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdv-gui"

  on_macos do
    on_intel do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv- gui_#{version}_darwin_x86_64.tar.gz"
      sha256 "5de3175a7f07d8678c0a27608f4237f9f4b63e499c47d9d3be7c0f846661dd40"
    end
    on_arm do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv- gui_#{version}_darwin_arm64.tar.gz"
      sha256 "ee9e121266d19aaea26956c74a635fa2b05317c1d1f7c191a48b5f854571d70b"
    end
  end

  # No zap stanza required
end
