# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdv-tui" do
  name "mdv-tui"
  desc "Terminal-based markdown viewer (TUI only)"
  homepage "https://github.com/iiatlas/mdv"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdv"

  on_linux do
    on_intel do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv-tui_#{version}_linux_x86_64.tar.gz"
      sha256 "69433c456de3a6e38daf1669e7bd9e6e99ae2b42ec051bc75c8c5ff62033629d"
    end
    on_arm do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv-tui_#{version}_linux_arm64.tar.gz"
      sha256 "fd329b2ed90cd5afdfa4eb46be27e0c080a7a5adbe83d2a88e00b7f1a1bce2ae"
    end
  end

  # No zap stanza required
end
