# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdv" do
  binary "mdv-gui"

  name "mdv"
  desc "Terminal-based markdown viewer with TUI and GUI modes"
  homepage "https://github.com/iiatlas/mdv"
  version "1.0.21"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdv"

  on_macos do
    on_intel do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv_#{version}_darwin_x86_64.tar.gz"
      sha256 "17765c4213c00e5bc1544d9854e134c42022424dbc628eba733f5886acdcc37e"
    end
    on_arm do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv_#{version}_darwin_arm64.tar.gz"
      sha256 "c07ae7dfa46a152c1c84335ae7680e15c53262aa39e236a943334798f87b98e7"
    end
  end

  # No zap stanza required
end
