# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdv" do
  binary "mdv-gui"

  name "mdv"
  desc "Terminal-based markdown viewer with TUI and GUI modes"
  homepage "https://github.com/iiatlas/mdv"
  version "1.0.22"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdv"

  on_macos do
    on_intel do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv_#{version}_darwin_x86_64.tar.gz"
      sha256 "8d83613141afbad0f382ce6476556be0ec317ac2c231426a12fd1c3d094746ae"
    end
    on_arm do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv_#{version}_darwin_arm64.tar.gz"
      sha256 "3c0d7a13087ea3e852e74fa885c3374d4c94b59517f9a8dd75b800ff213e5036"
    end
  end

  # No zap stanza required
end
