# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdv" do
  binary "mdv-gui"

  name "mdv"
  desc "Terminal-based markdown viewer with TUI and GUI modes"
  homepage "https://github.com/iiatlas/mdv"
  version "1.0.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdv"

  on_macos do
    on_intel do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv_#{version}_darwin_x86_64.tar.gz"
      sha256 "22cd50dfcb96e47944deac177fa2c5b77ebed1d9b1a007ad1657f09411a6f192"
    end
    on_arm do
      url "https://github.com/iiAtlas/mdv/releases/download/v#{version}/mdv_#{version}_darwin_arm64.tar.gz"
      sha256 "c59cd8637b69eb5ae2befb90ce77de1bd472102f7f3192cbd1b38c9fa3c50858"
    end
  end

  # No zap stanza required
end
