# This file was generated by GoReleaser. DO NOT EDIT.
cask "pidge" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "e11977abb57ad3cf4b7db791c3fdc003344d44ce1b08e0bfbc038a454b3b575e"
      url "https://github.com/iiAtlas/pidge-releases/releases/download/v#{version}/pidge_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a98e0ec0bdd18dcd1b656aae0a9c1dd8723af7fe83b6ef9c0d9b791e1e94cda4"
      url "https://github.com/iiAtlas/pidge-releases/releases/download/v#{version}/pidge_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2eadc9ef17739abb2b5c9a549972a5dff990f1ae69a52d16a3c85b820224aab"
      url "https://github.com/iiAtlas/pidge-releases/releases/download/v#{version}/pidge_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b787fde4636756abcd64f5912366f2b6d11436d7ac9ecad887eb003ea7c90d4"
      url "https://github.com/iiAtlas/pidge-releases/releases/download/v#{version}/pidge_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pidge"
  desc "Share a single HTML page, briefly."
  homepage "https://pidge.to"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pidge"
  manpage "cli/man/pidge.1"

  # No zap stanza required

end
