# typed: false
# frozen_string_literal: true

# This file was generated by pidge's release workflow. DO NOT EDIT.
class Pidge < Formula
  desc "Share HTML, Markdown, or text, briefly."
  homepage "https://pidge.to"
  version "0.1.6"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.6/pidge_0.1.6_darwin_arm64.tar.gz"
    sha256 "623ab6b0e4b8e8be9149d9df3deee3ca531c829d5719b76eabf5f38cc4cdfd55"
  elsif OS.mac?
    url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.6/pidge_0.1.6_darwin_amd64.tar.gz"
    sha256 "44d2ce9c4c040dd3ad37854e0fe02dc9ad45b88d52efc009105e2921afe3c66e"
  elsif OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.6/pidge_0.1.6_linux_arm64.tar.gz"
    sha256 "32e4352fcdb38e070a9908974b8f9f244c974ebd6dda777340cb1419cce68b47"
  elsif OS.linux?
    url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.6/pidge_0.1.6_linux_amd64.tar.gz"
    sha256 "c0f87beeafa097e86db43ac614fcc03ea27f8ba53227b1f296da8f5683fb5142"
  end

  def install
    bin.install "pidge"
    man1.install "cli/man/pidge.1"
  end

  test do
    system "#{bin}/pidge", "--version"
  end
end
