# typed: false
# frozen_string_literal: true

# This file was generated by pidge's release workflow. DO NOT EDIT.
class Pidge < Formula
  desc "Share HTML, Markdown, or text, briefly."
  homepage "https://pidge.to"
  version "0.1.8"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.8/pidge_0.1.8_darwin_arm64.tar.gz"
    sha256 "109f7d7cedf808940aed891a17d1d7a970396fc858fdf8d82327b111c3731e70"
  elsif OS.mac?
    url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.8/pidge_0.1.8_darwin_amd64.tar.gz"
    sha256 "629910dee735f588bd839398cbc7b708c32d3601f1dc340e9ad461e8ca695355"
  elsif OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.8/pidge_0.1.8_linux_arm64.tar.gz"
    sha256 "a769f3263f43e61415d0b2485f84caaa5720679d6fe3956c7b7219a7dbf3ca82"
  elsif OS.linux?
    url "https://github.com/iiAtlas/pidge-releases/releases/download/v0.1.8/pidge_0.1.8_linux_amd64.tar.gz"
    sha256 "cc8ba399934bcb8e5282d3e00a4b9dd9b9683683d3aae5cb04959e7fa93b279b"
  end

  def install
    bin.install "pidge"
    man1.install "cli/man/pidge.1"
  end

  test do
    system "#{bin}/pidge", "--version"
  end
end
